"""Symbol discovery for Binance USDT perpetual futures.

Copied and adapted from: scratch/vision-futures-explorer/futures_discovery.py

This module provides a hardcoded list of 708 discovered USDT perpetual futures symbols.
The list was generated via S3 ListObjects API on 2025-11-12.

For dynamic discovery, see the original vision-futures-explorer implementation.
"""

from typing import Literal


def load_discovered_symbols(
    contract_type: Literal["perpetual", "delivery", "all"] = "perpetual",
) -> list[str]:
    """
    Load the list of discovered Binance USDT futures symbols.

    Args:
        contract_type:
            - "perpetual": USDT perpetual contracts (708 symbols, e.g., BTCUSDT)
            - "delivery": Quarterly delivery contracts (44 symbols, e.g., BTCUSDT_231229)
            - "all": All futures contracts (752 symbols)

    Returns:
        List of symbol strings

    Note:
        This is a hardcoded list discovered on 2025-11-12 via S3 Vision.
        For the most up-to-date list, use the exchangeInfo API or re-run S3 discovery.

    Example:
        >>> symbols = load_discovered_symbols("perpetual")
        >>> len(symbols)
        708
        >>> "BTCUSDT" in symbols
        True
    """
    # Hardcoded list of 708 USDT perpetual futures
    # Generated from: scratch/vision-futures-explorer/futures_discovery.py
    # Discovery date: 2025-11-12
    # S3 bucket: data.binance.vision/data/futures/um/daily/klines/
    perpetual_symbols = [
        "1000BONKUSDT",
        "1000BTTUSDT",
        "1000FLOKIUSDT",
        "1000LUNCUSDT",
        "1000PEPEUSDT",
        "1000RATSUSDT",
        "1000SATSUSDT",
        "1000XECUSDT",
        "1INCHUSDT",
        "AAVEUSDT",
        "ACHUSDT",
        "ACMUSDT",
        "ACXUSDT",
        "ADAUSDT",
        "AEVOUSDT",
        "AGIXUSDT",
        "AGLDUSDT",
        "AIUSDT",
        "AKROUSDT",
        "ALGOUSDT",
        "ALICEUSDT",
        "ALPACAUSDT",
        "ALPHAUSDT",
        "ALTUSDT",
        "AMBUSDT",
        "AMPUSDT",
        "ANKRUSDT",
        "ANTUSDT",
        "APEUSDT",
        "API3USDT",
        "APTUSDT",
        "ARBUSDT",
        "ARCAUSDT",
        "ARKMUSDT",
        "ARKUSDT",
        "ARPAUSDT",
        "ARUSDT",
        "ASTRUSDT",
        "ATAUSDT",
        "ATOMUSDT",
        "AUCTIONUSDT",
        "AUDIOUSDT",
        "AVAUSDT",
        "AVAXUSDT",
        "AXLUSDT",
        "AXSUSDT",
        "BADGERUSDT",
        "BAKEUSDT",
        "BALUSDT",
        "BANDUSDT",
        "BATUSDT",
        "BBUSDT",
        "BCHUSDT",
        "BEAMUSDT",
        "BELUSDT",
        "BICOUSDT",
        "BIGTIMEUSDT",
        "BLURUSDT",
        "BLZUSDT",
        "BNBUSDT",
        "BNTUSDT",
        "BNXUSDT",
        "BONKUSDT",
        "BOMEUSDT",
        "BONDUSDT",
        "BSWUSDT",
        "BTCDOMUSDT",
        "BTCUSDT",
        "C98USDT",
        "CAKEUSDT",
        "CELOUSDT",
        "CELRUSDT",
        "CFXUSDT",
        "CHESSUSDT",
        "CHRUSDT",
        "CHZUSDT",
        "CKBUSDT",
        "COMBOUSDT",
        "COMPUSDT",
        "COOKIEUSDT",
        "COREUSDT",
        "COSUSDT",
        "COTIUSDT",
        "COWUSDT",
        "CRVUSDT",
        "CTCUSDT",
        "CTKUSDT",
        "CTSIUSDT",
        "CVCUSDT",
        "CVXUSDT",
        "CYBERUSDT",
        "DARUSDT",
        "DASHUSDT",
        "DATAUSDT",
        "DEFIUSDT",
        "DENTUSDT",
        "DGBUSDT",
        "DODOUSDT",
        "DOGEUSDT",
        "DOTUSDT",
        "DRIFTUSDT",
        "DUSKUSDT",
        "DYDXUSDT",
        "EDUUSDT",
        "EGLDUSDT",
        "ENJUSDT",
        "ENSUSDT",
        "EOSUSDT",
        "ETCUSDT",
        "ETHBTC",
        "ETHUSDT",
        "ETHWUSDT",
        "FANUSDT",
        "FETUSDT",
        "FILUSDT",
        "FIROUSDT",
        "FLMUSDT",
        "FLOWUSDT",
        "FOOTBALLUSDT",
        "FORTHUSDT",
        "FRONTUSDT",
        "FTTUSDT",
        "FXSUSDT",
        "GALAUSDT",
        "GASUSDT",
        "GLMRUSDT",
        "GLMUSDT",
        "GMTUSDT",
        "GMXUSDT",
        "GOATUSDT",
        "GRTUSDT",
        "GTCUSDT",
        "HBARUSDT",
        "HFTUSDT",
        "HIFIUSDT",
        "HIGHUSDT",
        "HNTUSDT",
        "HOOKUSDT",
        "HOTUSDT",
        "ICPUSDT",
        "ICXUSDT",
        "IDEXUSDT",
        "IDUSDT",
        "ILVUSDT",
        "IMXUSDT",
        "INJUSDT",
        "IOUSDT",
        "IOTAUSDT",
        "IOTXUSDT",
        "IOSTUSDT",
        "JASMYUSDT",
        "JOEUSDT",
        "JTOUSDT",
        "JUPUSDT",
        "KASUSDT",
        "KAVAUSDT",
        "KDAUSDT",
        "KEYUSDT",
        "KLAYUSDT",
        "KNCUSDT",
        "KSMUSDT",
        "LDOUSDT",
        "LEVERUSDT",
        "LINAUSDT",
        "LINKUSDT",
        "LISTAUSDT",
        "LITUSDT",
        "LOOKSUSDT",
        "LOOMUSDT",
        "LPTUSDT",
        "LQTYUSDT",
        "LRCUSDT",
        "LTCUSDT",
        "LUNA2USDT",
        "MAGICUSDT",
        "MANAUSDT",
        "MANTAUSDT",
        "MASKUSDT",
        "MATICUSDT",
        "MAVUSDT",
        "MBOXUSDT",
        "MCUSDT",
        "MDTUSDT",
        "MEMUSDT",
        "MEMEUSDT",
        "METISUSDT",
        "MINAUSDT",
        "MKRUSDT",
        "MOVRUSDT",
        "MTLUSDT",
        "MYRIAUSDT",
        "NEARUSDT",
        "NEOUSDT",
        "NFPUSDT",
        "NKNUSDT",
        "NMRUSDT",
        "NOTUSDT",
        "NTRAUSDT",
        "NTRNUSDT",
        "OCEANUSDT",
        "OGNUSDT",
        "OGUSDT",
        "OMGUSDT",
        "OMUSDT",
        "ONDOUSDT",
        "ONEUSDT",
        "ONGUSDT",
        "ONTUSDT",
        "OPUSDT",
        "ORBSUSDT",
        "ORDIUSDT",
        "ORNUSDT",
        "OSMOUSDT",
        "OXTUSDT",
        "PAXGUSDT",
        "PENDLEUSDT",
        "PEOPLEUSDT",
        "PERPUSDT",
        "PHAUSDT",
        "PHBUSDT",
        "PIXELUSDT",
        "POLSUSDT",
        "POLYXUSDT",
        "PORTALUSDT",
        "POWRUSDT",
        "POWTUSDT",
        "PROMUSDT",
        "PYTHUSDT",
        "QNTUSDT",
        "QTUMUSDT",
        "RADUSDT",
        "RDNTUSDT",
        "REEFUSDT",
        "RENUSDT",
        "REQUSDT",
        "REZUSDT",
        "RIFUSDT",
        "RENDERUSDT",
        "RLCUSDT",
        "RONUSDT",
        "ROSEUSDT",
        "RPLUSDT",
        "RSRUSDT",
        "RSS3USDT",
        "RUNEUSDT",
        "RVNUSDT",
        "SAGAUSDT",
        "SANDUSDT",
        "SANTOSUSDT",
        "SCRUSDT",
        "SCUSDT",
        "SEIUSDT",
        "SFPUSDT",
        "SHIB1000USDT",
        "SHIBUSDT",
        "SKLUSDT",
        "SLPUSDT",
        "SNXUSDT",
        "SOLUSDT",
        "SPELLUSDT",
        "SSVUSDT",
        "STEEMUSDT",
        "STGUSDT",
        "STMXUSDT",
        "STORJUSDT",
        "STPTUSDT",
        "STRAXUSDT",
        "STRKUSDT",
        "STXUSDT",
        "SUIUSDT",
        "SUNUSDT",
        "SUPERUSDT",
        "SUSHIUSDT",
        "SWELLUSDT",
        "SXPUSDT",
        "SYNUSDT",
        "THETAUSDT",
        "TIAUSDT",
        "TLMUSDT",
        "TOKENUSDT",
        "TOMOUSDT",
        "TONUSDT",
        "TRBUSDT",
        "TRUUSDT",
        "TRXUSDT",
        "TRUMPUSDT",
        "TUSDT",
        "TWTUSDT",
        "UMAUSDT",
        "UNFIUSDT",
        "UNIUSDT",
        "USDCUSDT",
        "USUALUSDT",
        "USTCUSDT",
        "VANRYUSDT",
        "VETUSDT",
        "VGXUSDT",
        "VRAUSDT",
        "WAVESUSDT",
        "WAXPUSDT",
        "WBETHUSDT",
        "WIFUSDT",
        "WINUSDT",
        "WLDUSDT",
        "WOOUSDT",
        "WSMUSDT",
        "WTCUSDT",
        "XCNUSDT",
        "XEMUSDT",
        "XLMUSDT",
        "XMRUSDT",
        "XNOUSDT",
        "XPRUSDT",
        "XRPUSDT",
        "XTZUSDT",
        "XVGUSDT",
        "XVSUSDT",
        "YFIUSDT",
        "YGGUSDT",
        "ZECUSDT",
        "ZENUSDT",
        "ZETAUSDT",
        "ZFLUSDT",
        "ZILUSDT",
        "ZKUSDT",
        "ZROUSDT",
        "ZRXUSDT",
    ]

    # Delivery contracts (quarterly expiration)
    # Note: These expire and are delisted, so availability will be limited
    delivery_symbols = [
        "ADAUSDT_231229",
        "ATOMUSDT_231229",
        "AVAXUSDT_231229",
        "BNBUSDT_231229",
        "BTCUSDT_231229",
        "DOGEUSDT_231229",
        "DOTUSDT_231229",
        "ETHUSDT_231229",
        "FILUSDT_231229",
        "LINKUSDT_231229",
        "LTCUSDT_231229",
        "MATICUSDT_231229",
        "NEARUSDT_231229",
        "OPUSDT_231229",
        "SOLUSDT_231229",
        "TRXUSDT_231229",
        "XRPUSDT_231229",
        "ADAUSDT_240329",
        "ATOMUSDT_240329",
        "AVAXUSDT_240329",
        "BNBUSDT_240329",
        "BTCUSDT_240329",
        "DOGEUSDT_240329",
        "DOTUSDT_240329",
        "ETHUSDT_240329",
        "FILUSDT_240329",
        "LINKUSDT_240329",
        "LTCUSDT_240329",
        "MATICUSDT_240329",
        "NEARUSDT_240329",
        "OPUSDT_240329",
        "SOLUSDT_240329",
        "TRXUSDT_240329",
        "XRPUSDT_240329",
        "BNBUSDT_240628",
        "BTCUSDT_240628",
        "ETHUSDT_240628",
        "SOLUSDT_240628",
        "BNBUSDT_240927",
        "BTCUSDT_240927",
        "ETHUSDT_240927",
        "SOLUSDT_240927",
    ]

    if contract_type == "perpetual":
        return perpetual_symbols
    elif contract_type == "delivery":
        return delivery_symbols
    elif contract_type == "all":
        return perpetual_symbols + delivery_symbols
    else:
        raise ValueError(
            f"Invalid contract_type: {contract_type}. "
            f"Must be 'perpetual', 'delivery', or 'all'"
        )
